### ISSUE TITLE
new Installation of mmm-shelly-pm: module "request" not found

### ISSUE THREAD

**Issue by torth** [Medve01/Shelly-HT#3]
I've just installed MMM-Shelly-PM for first time and receive an error when I restart my config. As described I just used git clone for installation:

0|MagicMirror  | [10.09.2022 15:57.13.008] [ERROR]
0|MagicMirror  | App threw an error during load
0|MagicMirror  | [10.09.2022 15:57.13.012] [ERROR] Error: Cannot find module 'request'
0|MagicMirror  | Require stack:
0|MagicMirror  | - /home/pi/MagicMirror/modules/MMM-Shelly-PM/node_helper.js
0|MagicMirror  | - /home/pi/MagicMirror/js/app.js
0|MagicMirror  | - /home/pi/MagicMirror/js/electron.js
0|MagicMirror  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|MagicMirror  | -
0|MagicMirror  |     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
0|MagicMirror  |     at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
0|MagicMirror  |     at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|MagicMirror  |     at Module._load (node:internal/modules/cjs/loader:785:27)
0|MagicMirror  |     at c._load (node:electron/js2c/asar_bundle:5:13343)
0|MagicMirror  |     at Module.require (node:internal/modules/cjs/loader:1012:19)
0|MagicMirror  |     at require (node:internal/modules/cjs/helpers:102:18)
0|MagicMirror  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Shelly-PM/node_helper.js:3:17)
0|MagicMirror  |     at Module._compile (node:internal/modules/cjs/loader:1118:14)
0|MagicMirror  |     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
0|MagicMirror  | [10.09.2022 15:57.13.018] [ERROR] Whoops! There was an uncaught exception...
0|MagicMirror  | [10.09.2022 15:57.13.034] [ERROR]
0|MagicMirror  | Error: Cannot find module 'request'
0|MagicMirror  | Require stack:
0|MagicMirror  | - /home/pi/MagicMirror/modules/MMM-Shelly-PM/node_helper.js
0|MagicMirror  | - /home/pi/MagicMirror/js/app.js
0|MagicMirror  | - /home/pi/MagicMirror/js/electron.js
0|MagicMirror  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|MagicMirror  | -
0|MagicMirror  |     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
0|MagicMirror  |     at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
0|MagicMirror  |     at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|MagicMirror  |     at Module._load (node:internal/modules/cjs/loader:785:27)
0|MagicMirror  |     at c._load (node:electron/js2c/asar_bundle:5:13343)
0|MagicMirror  |     at Module.require (node:internal/modules/cjs/loader:1012:19)
0|MagicMirror  |     at require (node:internal/modules/cjs/helpers:102:18)
0|MagicMirror  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Shelly-PM/node_helper.js:3:17)
0|MagicMirror  |     at Module._compile (node:internal/modules/cjs/loader:1118:14)
0|MagicMirror  |     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10) {
0|MagicMirror  |   code: 'MODULE_NOT_FOUND',
0|MagicMirror  |   requireStack: [
0|MagicMirror  |     '/home/pi/MagicMirror/modules/MMM-Shelly-PM/node_helper.js',
0|MagicMirror  |     '/home/pi/MagicMirror/js/app.js',
0|MagicMirror  |     '/home/pi/MagicMirror/js/electron.js',
0|MagicMirror  |     '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
0|MagicMirror  |     undefined
0|MagicMirror  |   ]
0|MagicMirror  | }
0|MagicMirror  | [10.09.2022 15:57.13.036] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?

**Comment by torth** [comment]
wrong project - sorry
